name: train-my-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
 
      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
 
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py
 
          echo "## Metrik Model" >> report.md
          cat metrics.txt >> report.md

          echo "## Visualisasi Model" >> report.md
          cml publish feature_importance.png --md >> report.md
          cml publish confusion_matrix.png --md >> report.md
          
          cml send-comment report.md